### ISSUE TITLE
Documentation upgrade: vst2 is discontinued

### ISSUE THREAD

**Issue by sashker** [dudk/vst2#2]
Since vst2 is obsolete than README looks a little bit ambiguous. The Steinberg site offers to download vst3 SDK version at the moment, so for newcomers, it's not obvious what they should do next: to download vst3, to try to find a vst2 archive etc.

Would you mind explaining this on the README page, please?

P.S. Does it make sense to use vst2 if it's discontinued? Or the naming of the project doesn't mean that it relies on the vst2 exactly?

**Comment by dudk** [comment]
Very good point. Currently it's impossible to get VST2 SDK seprately, but it's still included in VST3 SDK. 

The problem is that this package is built on VST2 2.4 and header file names has changed since then. It would make a lot of sense to update this project to this new version. So, for this not only README change will be required. 

Regads your last question, it's one of the hottest discussions in VST community. If I would develop plugin, it would be reasonable to do it with VST3. But here you should keep in mind that some apps like Ableton Live and Reason still support VST2 only.

If you are creating host application, support of VST2 will make make even more sense beacause there are a plenty of VST2-only plugins there. 

I've created new [issue](https://github.com/dudk/vst2/issues/3) about migrating to latest publicly available version of VST2 SDK. So, if I answered your questions, please close this one. Thanks!

**Comment by sashker** [comment]
Thank you for the detailed explanation. I just noticed that the naming of header files is changed in vst3 since I don't follow the development of the VST project. 

Hope, migration to the latest version of the VST2 which included in the VST3 SDK won't be a big problem.
